version: '3.1'

services:

  wordpress:
    image: wordpress
    restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: umwgeg
      WORDPRESS_DB_NAME: WinJayDB
    volumes:
      - /mnt/001.WinJay.cn/www:/var/www/html
#      - wordpress:/var/www/html

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: WinJayDB
      MYSQL_USER: root
      MYSQL_PASSWORD: umwgeg
      MYSQL_RANDOM_ROOT_PASSWORD: 'umwgeg'
    volumes:
      - /mnt/001.WinJay.cn/db-data:/var/lib/mysql
#      - db:/var/lib/mysql

#volumes:
#  wordpress: /mnt/001.WinJay.cn/www
#  db: mnt/001.WinJay.cn/db-data
